let rootFactory=null,renderQueued=false,nodeSeq=1,callbackSeq=1;const callbacks=new Map();
const fallbackHost={commit(tree){globalThis.__ZIGUI_LAST_TREE__=tree;globalThis.dispatchEvent?.(new CustomEvent("zigui:commit",{detail:tree}));},async invoke(module,method,args){if(globalThis.__ZIGUI_WEB_NATIVE__?.[module]?.[method])return globalThis.__ZIGUI_WEB_NATIVE__[module][method](...args);throw new Error(`Native module unavailable: ${module}.${method}`);}};
const host=()=>globalThis.__ZIGUI_NATIVE__??fallbackHost;const resolve=v=>typeof v==="function"?v():v;
function registerCallback(fn){const id=callbackSeq++;callbacks.set(id,fn);return{__callback:id};}
function normalize(input){if(input==null||input===false)return null;if(Array.isArray(input))return input.map(normalize).filter(Boolean);if(["string","number","bigint"].includes(typeof input))return{id:nodeSeq++,type:"Text",props:{text:String(input)},children:[]};if(!input.__ziguiNode)throw new TypeError(`Unsupported ZigUI node: ${String(input)}`);const props={};for(const[key,raw]of Object.entries(input.props??{})){if(key==="children"||key==="child")continue;if(/^on[A-Z]/.test(key)&&typeof raw==="function")props[key]=registerCallback(raw);else props[key]=resolve(raw);}const source=input.props?.children??(input.props?.child===undefined?[]:[input.props.child]);const children=normalize(source)??[];return{id:nodeSeq++,type:input.type,props,children:Array.isArray(children)?children:[children]};}
function renderNow(){if(!rootFactory)return;nodeSeq=1;callbacks.clear();host().commit(normalize(rootFactory()));}
function scheduleRender(){if(renderQueued||!rootFactory)return;renderQueued=true;queueMicrotask(()=>{renderQueued=false;renderNow();});}
export function signal(initial){let value=initial;const subscribers=new Set();return{get value(){return value},set value(next){if(Object.is(value,next))return;value=next;subscribers.forEach(fn=>fn(next));scheduleRender();},update(fn){this.value=fn(value)},subscribe(fn){subscribers.add(fn);return()=>subscribers.delete(fn)}}}export const state=signal;
export function component(type){return(props={})=>({__ziguiNode:true,type,props})}
export const Screen=component("Screen"),SafeArea=component("SafeArea"),Column=component("Column"),Row=component("Row"),Stack=component("Stack"),ScrollView=component("ScrollView"),List=component("List"),Text=component("Text"),Button=component("Button"),TextInput=component("TextInput"),Image=component("Image"),Switch=component("Switch"),Slider=component("Slider"),Progress=component("Progress"),Spacer=component("Spacer"),Divider=component("Divider"),Card=component("Card");
export function App(factory){if(typeof factory!=="function")throw new TypeError("App(factory) requires a function");rootFactory=factory;scheduleRender();}
export function __dispatchNativeEvent(callbackId,payload){const fn=callbacks.get(Number(callbackId));if(!fn)return false;fn(payload);return true}
export function __refresh(){renderNow()}export function platform(){return globalThis.__ZIGUI_PLATFORM__??"web"}
export const Native=new Proxy({},{get(_t,module){return new Proxy({},{get(_m,method){return(...args)=>host().invoke(String(module),String(method),args)}})}});
