import fs from "node:fs/promises";
import fssync from "node:fs";
import path from "node:path";
import http from "node:http";
import { spawn } from "node:child_process";
import { fileURLToPath } from "node:url";

const here=path.dirname(fileURLToPath(import.meta.url));
const templateRoot=path.resolve(here,"../templates/basic");

async function copyDir(src,dest){await fs.mkdir(dest,{recursive:true});for(const ent of await fs.readdir(src,{withFileTypes:true})){const s=path.join(src,ent.name),d=path.join(dest,ent.name);if(ent.isDirectory())await copyDir(s,d);else await fs.copyFile(s,d);}}
export async function create(name,cwd=process.cwd()){if(!/^[a-zA-Z][a-zA-Z0-9-_]*$/.test(name))throw new Error("Project name must be alphanumeric with - or _");const dest=path.resolve(cwd,name);if(fssync.existsSync(dest))throw new Error("Path already exists: "+dest);await copyDir(templateRoot,dest);const p=path.join(dest,"package.json");const pkg=JSON.parse(await fs.readFile(p,"utf8"));pkg.name=name.toLowerCase();await fs.writeFile(p,JSON.stringify(pkg,null,2)+"\n");return dest;}
function mime(file){if(file.endsWith(".js"))return"text/javascript";if(file.endsWith(".html"))return"text/html";if(file.endsWith(".css"))return"text/css";if(file.endsWith(".json"))return"application/json";return"application/octet-stream";}
export async function buildWeb(projectDir,outDir="dist/web"){const root=path.resolve(projectDir),out=path.resolve(root,outDir);await fs.rm(out,{recursive:true,force:true});await fs.mkdir(out,{recursive:true});const app=await fs.readFile(path.join(root,"src/app.js"),"utf8");const ui=await fs.readFile(path.resolve(here,"../../ui/src/index.js"),"utf8");await fs.writeFile(path.join(out,"zigui.js"),ui);await fs.writeFile(path.join(out,"app.js"),app.replaceAll('"@zigui/ui"','"./zigui.js"').replaceAll("'@zigui/ui'","'./zigui.js'"));await fs.writeFile(path.join(out,"web-host.js"),WEB_HOST);await fs.writeFile(path.join(out,"index.html"),HTML);return out;}
export async function devWeb(projectDir,port=5179){const root=path.resolve(projectDir),out=await buildWeb(root,".zigui/dev-web"),clients=new Set();const server=http.createServer(async(req,res)=>{if(req.url==="/__zigui_events"){res.writeHead(200,{"Content-Type":"text/event-stream","Cache-Control":"no-cache","Connection":"keep-alive"});clients.add(res);req.on("close",()=>clients.delete(res));return;}const rel=req.url==="/"?"index.html":req.url.slice(1).split("?")[0],file=path.join(out,rel);try{const b=await fs.readFile(file);res.writeHead(200,{"Content-Type":mime(file),"Cache-Control":"no-store"});res.end(b);}catch{res.writeHead(404);res.end("Not found");}});server.listen(port,"127.0.0.1",()=>console.log("[zui] web dev http://127.0.0.1:"+port));fssync.watch(path.join(root,"src"),{recursive:true},async()=>{try{await buildWeb(root,".zigui/dev-web");clients.forEach(c=>c.write("data: reload\n\n"));console.log("[zui] hot reload");}catch(e){console.error(e.message);}});}
function commandExists(cmd){return new Promise(resolve=>{const p=spawn(cmd,["--version"],{stdio:"ignore"});p.on("error",()=>resolve(false));p.on("exit",c=>resolve(c===0));});}
export async function doctor(){const checks={};for(const cmd of["node","npm","bun","zig","java","adb","gradle","xcodebuild"])checks[cmd]=await commandExists(cmd);console.table(checks);return checks;}
export async function buildAndroid(){const checks=await doctor();if(!checks.zig)throw new Error("Zig compiler not found. Install Zig 0.14+ and run again.");if(!process.env.ANDROID_HOME&&!process.env.ANDROID_SDK_ROOT)throw new Error("ANDROID_HOME/ANDROID_SDK_ROOT is not configured.");throw new Error("Android native packaging pipeline is scaffolded but not yet production-complete in v0.2 alpha. See docs/ANDROID.md.");}
export async function main(args){const[cmd,a,b,...rest]=args;if(!cmd||["-h","--help","help"].includes(cmd)){console.log(HELP);return;}if(cmd==="create"){const d=await create(a);console.log("[zui] created "+d+"\nNext: cd "+a+" && npm install && npm run dev");return;}if(cmd==="doctor"){await doctor();return;}if(cmd==="dev"&&a==="web"){await devWeb(b??".",Number(rest[0]??5179));return;}if(cmd==="build"&&a==="web"){const out=await buildWeb(b??".");console.log("[zui] built "+out);return;}if(cmd==="build"&&a==="android"){await buildAndroid(b??".");return;}throw new Error("Unknown command: "+args.join(" "));}
const HELP="ZigUI CLI\n\n  zui create <name>\n  zui doctor\n  zui dev web [project] [port]\n  zui build web [project]\n  zui build android [project]\n";
const HTML='<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ZigUI</title><style>body{margin:0;font-family:system-ui;background:#f6f7f9}*{box-sizing:border-box}button,input{font:inherit}</style></head><body><div id="app"></div><script type="module" src="./web-host.js"></script></body></html>';
const WEB_HOST=`
import { __dispatchNativeEvent } from './zigui.js';
globalThis.__ZIGUI_PLATFORM__='web';
const root=document.getElementById('app');
function px(v){return typeof v==='number'?v+'px':v}
function style(el,p){if(p.padding!=null)el.style.padding=px(p.padding);if(p.gap!=null)el.style.gap=px(p.gap);if(p.fontSize!=null)el.style.fontSize=px(p.fontSize);if(p.width!=null)el.style.width=px(p.width);if(p.height!=null)el.style.height=px(p.height);if(p.background)el.style.background=p.background;if(p.color)el.style.color=p.color;if(p.borderRadius!=null)el.style.borderRadius=px(p.borderRadius);if(p.flex!=null)el.style.flex=String(p.flex);}
function make(n){if(!n)return document.createComment('null');let e;switch(n.type){case'Text':e=document.createElement('div');e.textContent=n.props.text??'';break;case'Button':e=document.createElement('button');e.textContent=n.props.text??'Button';break;case'TextInput':e=document.createElement('input');e.value=n.props.value??'';e.placeholder=n.props.placeholder??'';break;case'Image':e=document.createElement('img');e.src=n.props.src??'';break;case'Switch':e=document.createElement('input');e.type='checkbox';e.checked=!!n.props.value;break;default:e=document.createElement('div');}if(n.type==='Column'){e.style.display='flex';e.style.flexDirection='column'}if(n.type==='Row'){e.style.display='flex';e.style.flexDirection='row'}if(n.type==='Screen'){e.style.minHeight='100vh'}if(n.type==='ScrollView'){e.style.overflow='auto'}style(e,n.props||{});for(const[k,v]of Object.entries(n.props||{})){if(k.startsWith('on')&&v?.__callback){const ev=k==='onPress'?'click':k==='onChange'?'input':k.slice(2).toLowerCase();e.addEventListener(ev,x=>__dispatchNativeEvent(v.__callback,k==='onChange'?x.target.value:{type:ev}));}}for(const c of n.children||[])e.appendChild(make(c));return e;}
globalThis.__ZIGUI_NATIVE__={commit(tree){root.replaceChildren(make(tree));},async invoke(module,method,args){return globalThis.__ZIGUI_WEB_NATIVE__?.[module]?.[method]?.(...args);}};
await import('./app.js?'+Date.now());
const es=new EventSource('/__zigui_events');es.onmessage=e=>{if(e.data==='reload')location.reload()};
`;
