const TYPES={Screen:{container:true,defaults:{background:'#f8fafc'}},Column:{container:true,defaults:{padding:24,gap:12}},Row:{container:true,defaults:{gap:10}},Card:{container:true,defaults:{padding:12,borderRadius:12}},ScrollView:{container:true,defaults:{}},Text:{defaults:{text:'Text',fontSize:18,color:'#111827'}},Button:{defaults:{text:'Button'}},TextInput:{defaults:{placeholder:'Type here...'}},Image:{defaults:{src:'https://placehold.co/320x180',height:180}},Switch:{defaults:{value:false}},Progress:{defaults:{value:50}},Spacer:{defaults:{height:16}},Divider:{defaults:{height:1,background:'#d1d5db'}}};
let model,selectedId=null,history=[],future=[],saving=false;
const $=s=>document.querySelector(s),palette=$('#palette'),tree=$('#tree'),canvas=$('#canvas'),inspector=$('#inspector'),device=$('#device'),code=$('#code'),status=$('#status');
const uid=()=>Math.random().toString(36).slice(2,9);
function node(type){return{id:uid(),type,props:{...TYPES[type].defaults},children:TYPES[type].container?[]:[]}}
function defaultModel(){const root=node('Screen'),col=node('Column');const title=node('Text');title.props.text='Hello ZigUI';title.props.fontSize=30;const btn=node('Button');btn.props.text='Get Started';col.children.push(title,btn);root.children.push(col);return{version:1,root}}
function clone(v){return JSON.parse(JSON.stringify(v))}
function pushHistory(){history.push(clone(model));if(history.length>80)history.shift();future=[]}
function find(n,id,parent=null){if(n.id===id)return{node:n,parent};for(const c of n.children||[]){const r=find(c,id,n);if(r)return r}return null}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function px(v){return typeof v==='number'?v+'px':v}
function applyStyle(el,p){for(const k of ['padding','gap','fontSize','width','height','borderRadius','margin'])if(p[k]!=null)el.style[k]=px(p[k]);for(const k of ['background','color'])if(p[k])el.style[k]=p[k];if(p.align)el.style.alignItems=p.align;if(p.justify)el.style.justifyContent=p.justify;if(p.flex!=null)el.style.flex=p.flex}
function renderNode(n){let el=document.createElement('div');el.dataset.id=n.id;el.className='node';switch(n.type){case'Screen':el.classList.add('z-screen');break;case'Column':el.classList.add('z-column');break;case'Row':el.classList.add('z-row');break;case'Card':el.classList.add('z-card');break;case'ScrollView':el.style.overflow='auto';break;case'Text':el.classList.add('z-text');el.textContent=n.props.text??'';break;case'Button':el=document.createElement('button');el.dataset.id=n.id;el.className='node z-button';el.textContent=n.props.text??'Button';break;case'TextInput':el=document.createElement('input');el.dataset.id=n.id;el.className='node z-input';el.placeholder=n.props.placeholder??'';el.value=n.props.value??'';break;case'Image':el=document.createElement('img');el.dataset.id=n.id;el.className='node';el.src=n.props.src??'';el.style.objectFit='cover';el.style.maxWidth='100%';break;case'Switch':el=document.createElement('input');el.type='checkbox';el.dataset.id=n.id;el.className='node';el.checked=!!n.props.value;break;case'Progress':el=document.createElement('progress');el.dataset.id=n.id;el.className='node';el.value=Number(n.props.value??0);el.max=100;break;case'Spacer':el.classList.add('z-spacer');break;case'Divider':break}applyStyle(el,n.props);if(n.id===selectedId)el.classList.add('selected');el.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();selectedId=n.id;renderAll()});el.draggable=n.type!=='Screen';el.addEventListener('dragstart',e=>e.dataTransfer.setData('application/zigui-node',n.id));if(TYPES[n.type].container){el.addEventListener('dragover',e=>{e.preventDefault();el.classList.add('drop-target')});el.addEventListener('dragleave',()=>el.classList.remove('drop-target'));el.addEventListener('drop',e=>{e.preventDefault();e.stopPropagation();el.classList.remove('drop-target');handleDrop(e,n.id)});for(const c of n.children)el.appendChild(renderNode(c))}return el}
function renderCanvas(){canvas.replaceChildren(renderNode(model.root))}
function treeHtml(n,depth=0){return`<div class="tree-node ${n.id===selectedId?'active':''}" data-tree-id="${n.id}" style="padding-left:${depth*14+4}px">${esc(n.type)} <span class="small">${esc(n.props.text??'')}</span></div>`+(n.children||[]).map(c=>treeHtml(c,depth+1)).join('')}
function renderTree(){tree.innerHTML=treeHtml(model.root);tree.querySelectorAll('[data-tree-id]').forEach(e=>e.onclick=()=>{selectedId=e.dataset.treeId;renderAll()})}
const fields={text:'text',placeholder:'text',src:'text',padding:'number',gap:'number',fontSize:'number',width:'number',height:'number',borderRadius:'number',background:'color',color:'color',align:'select',justify:'select',value:'text'};
function renderInspector(){const f=find(model.root,selectedId);if(!f){inspector.innerHTML='<p>Select an element.</p>';return}const n=f.node;let html=`<b>${n.type}</b><div class="small">${n.id}</div>`;for(const [key,type] of Object.entries(fields)){if(!(key in n.props)&&!['padding','gap','width','height','background','color','borderRadius','align','justify'].includes(key))continue;const val=n.props[key]??'';if(type==='select')html+=`<div class="field"><label>${key}</label><select data-prop="${key}"><option value="">default</option>${['flex-start','center','flex-end','stretch','space-between','space-around'].map(v=>`<option ${val===v?'selected':''}>${v}</option>`).join('')}</select></div>`;else html+=`<div class="field"><label>${key}</label><input data-prop="${key}" type="${type}" value="${esc(val)}"></div>`}html+=`<button id="duplicate">Duplicate</button> ${n.type!=='Screen'?'<button id="delete" class="danger">Delete</button>':''}`;inspector.innerHTML=html;inspector.querySelectorAll('[data-prop]').forEach(el=>el.oninput=()=>{pushHistory();const v=el.type==='number'?(el.value===''?undefined:Number(el.value)):el.value;if(v===undefined||v==='')delete n.props[el.dataset.prop];else n.props[el.dataset.prop]=v;renderCanvas();renderTree();scheduleSave()});$('#duplicate')?.addEventListener('click',()=>{if(!f.parent)return;pushHistory();const c=clone(n);const reid=x=>{x.id=uid();(x.children||[]).forEach(reid)};reid(c);f.parent.children.splice(f.parent.children.indexOf(n)+1,0,c);selectedId=c.id;renderAll();scheduleSave()});$('#delete')?.addEventListener('click',()=>{if(!f.parent)return;pushHistory();f.parent.children=f.parent.children.filter(x=>x.id!==n.id);selectedId=f.parent.id;renderAll();scheduleSave()})}
function renderAll(){renderCanvas();renderTree();renderInspector()}
function removeNode(id){const f=find(model.root,id);if(!f?.parent)return null;const i=f.parent.children.findIndex(x=>x.id===id);return f.parent.children.splice(i,1)[0]}
function handleDrop(e,targetId){const type=e.dataTransfer.getData('application/zigui-type'),existing=e.dataTransfer.getData('application/zigui-node');const target=find(model.root,targetId)?.node;if(!target||!TYPES[target.type].container)return;pushHistory();if(type){const n=node(type);target.children.push(n);selectedId=n.id}else if(existing&&existing!==targetId){const moved=removeNode(existing);if(moved&&!find(moved,targetId))target.children.push(moved);selectedId=existing}renderAll();scheduleSave()}
function scheduleSave(){status.textContent='Unsaved';clearTimeout(saving);saving=setTimeout(save,250)}
async function save(){const r=await fetch('/api/model',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(model)});const data=await r.json();code.value=data.source??code.value;status.textContent='Saved'}
async function load(){const r=await fetch('/api/model');model=await r.json();if(!model?.root)model=defaultModel();selectedId=model.root.id;const s=await fetch('/api/source');code.value=await s.text();renderAll()}
for(const type of Object.keys(TYPES)){const d=document.createElement('div');d.className='palette-item';d.draggable=true;d.textContent=type;d.addEventListener('dragstart',e=>e.dataTransfer.setData('application/zigui-type',type));palette.appendChild(d)}
canvas.addEventListener('dragover',e=>e.preventDefault());canvas.addEventListener('drop',e=>{if(e.target===canvas)handleDrop(e,model.root.id)});
document.querySelectorAll('[data-device]').forEach(b=>b.onclick=()=>{device.className='device '+b.dataset.device});$('#save').onclick=save;$('#undo').onclick=()=>{if(!history.length)return;future.push(clone(model));model=history.pop();renderAll();scheduleSave()};$('#redo').onclick=()=>{if(!future.length)return;history.push(clone(model));model=future.pop();renderAll();scheduleSave()};$('#applyCode').onclick=async()=>{await fetch('/api/source',{method:'POST',headers:{'content-type':'text/plain'},body:code.value});status.textContent='Code applied'};$('#refreshCode').onclick=async()=>code.value=await(await fetch('/api/source')).text();
load();
