const TYPES={Screen:{container:true,defaults:{background:'#fff'}},Frame:{container:true,defaults:{name:'Frame',width:320,height:240,layout:'absolute'}},Column:{container:true,defaults:{padding:16,gap:8}},Row:{container:true,defaults:{gap:8}},Card:{container:true,defaults:{padding:12,borderRadius:10,background:'#fff'}},ScrollView:{container:true,defaults:{}},Text:{defaults:{text:'Text',fontSize:18,color:'#111'}},Button:{defaults:{text:'Button',background:'#0d63ce',color:'#fff',borderRadius:6}},TextInput:{defaults:{placeholder:'Type here…'}},Image:{defaults:{src:'https://placehold.co/320x180',width:320,height:180}},Shape:{defaults:{width:120,height:80,background:'#d1d5db',borderRadius:0}},Svg:{defaults:{source:'<svg></svg>',width:120,height:120}},WebEmbed:{defaults:{html:'',css:'',width:320,height:240}},Switch:{defaults:{value:false}},Progress:{defaults:{value:50}},Spacer:{defaults:{height:16}},Divider:{defaults:{height:1,background:'#ddd'}}};
let model=null,selected=[],history=[],future=[],saveTimer=null,zoom=1;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const tree=$('#tree'),canvas=$('#canvas'),inspector=$('#inspector'),device=$('#device'),code=$('#code'),status=$('#status'),palette=$('#palette'),tokens=$('#tokens');
const uid=(p='n')=>`${p}_${Math.random().toString(36).slice(2,9)}`;
const clone=v=>JSON.parse(JSON.stringify(v));
function node(type){return{id:uid(type.toLowerCase()),type,props:{...TYPES[type].defaults},children:[]}}
function pushHistory(){history.push(clone(model));if(history.length>100)history.shift();future=[]}
function find(n,id,parent=null){if(n.id===id)return{node:n,parent};for(const c of n.children||[]){const r=find(c,id,n);if(r)return r}return null}
function findAll(){return selected.map(id=>find(model.root,id)?.node).filter(Boolean)}
function esc(s){return String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
const px=v=>typeof v==='number'?`${v}px`:v;
function style(el,p,n){
  const map=['width','height','minWidth','minHeight','padding','paddingTop','paddingRight','paddingBottom','paddingLeft','gap','fontSize','lineHeight','letterSpacing','borderRadius','borderWidth','margin'];for(const k of map)if(p[k]!=null)el.style[k]=px(p[k]);
  for(const k of ['background','color','borderColor','boxShadow','fontFamily','textAlign','opacity'])if(p[k]!=null)el.style[k]=String(p[k]);
  if(p.fontWeight!=null)el.style.fontWeight=p.fontWeight;if(p.rotation)el.style.transform=`rotate(${p.rotation}deg)`;
  if(p.layout==='absolute'&&n.type==='Frame')el.style.position='relative'; if(p.x!=null||p.y!=null){el.style.position='absolute';if(p.x!=null)el.style.left=px(p.x);if(p.y!=null)el.style.top=px(p.y)}
  if(p.layout==='column'||n.type==='Column'){el.style.display='flex';el.style.flexDirection='column'} if(p.layout==='row'||n.type==='Row'){el.style.display='flex';el.style.flexDirection='row'}
  if(p.wrap)el.style.flexWrap='wrap'; if(p.align)el.style.alignItems=p.align;if(p.justify)el.style.justifyContent=p.justify;
  if(p.visible===false)el.style.opacity=.28;
}
function renderNode(n){let el;switch(n.type){case'Text':el=document.createElement('div');el.className='node z-text';el.textContent=n.props.text??'';break;case'Button':el=document.createElement('button');el.className='node z-button';el.textContent=n.props.text??'Button';break;case'TextInput':el=document.createElement('input');el.className='node z-input';el.placeholder=n.props.placeholder??'';el.value=n.props.value??'';break;case'Image':el=document.createElement('img');el.className='node';el.src=n.props.src??'';el.style.objectFit='cover';break;case'Switch':el=document.createElement('input');el.type='checkbox';el.className='node';el.checked=!!n.props.value;break;case'Progress':el=document.createElement('progress');el.className='node';el.max=100;el.value=Number(n.props.value??0);break;case'Svg':el=document.createElement('div');el.className='node';el.innerHTML=n.props.source??'';break;case'WebEmbed':el=document.createElement('div');el.className='node z-web';el.textContent='Imported Web Bundle';break;default:el=document.createElement('div');el.className='node '+(n.type==='Column'?'z-column':n.type==='Row'?'z-row':n.type==='Card'?'z-card':n.type==='Shape'?'z-shape':'z-frame');}
  el.dataset.id=n.id;style(el,n.props,n);if(selected.includes(n.id))el.classList.add(selected[0]===n.id?'selected':'multi');
  el.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();if(e.shiftKey){selected=selected.includes(n.id)?selected.filter(x=>x!==n.id):[...selected,n.id]}else selected=[n.id];renderAll()});
  el.draggable=n.type!=='Screen';el.addEventListener('dragstart',e=>e.dataTransfer.setData('application/zigui-node',n.id));
  if(TYPES[n.type]?.container){el.addEventListener('dragover',e=>{e.preventDefault();el.classList.add('drop-target')});el.addEventListener('dragleave',()=>el.classList.remove('drop-target'));el.addEventListener('drop',e=>{e.preventDefault();e.stopPropagation();el.classList.remove('drop-target');drop(e,n.id)});for(const c of n.children||[])el.appendChild(renderNode(c))}
  return el;
}
function renderCanvas(){canvas.replaceChildren(renderNode(model.root))}
function treeHtml(n,d=0){const active=selected.includes(n.id)?'active':'';const name=n.props?.name||n.props?.text||n.type;return`<div class="tree-node ${active}" data-id="${n.id}" style="padding-left:${d*12+4}px"><span>${esc(n.type)}</span><span style="color:#999;overflow:hidden;text-overflow:ellipsis">${esc(name)}</span></div>`+(n.children||[]).map(c=>treeHtml(c,d+1)).join('')}
function renderTree(){tree.innerHTML=treeHtml(model.root);$$('.tree-node[data-id]').forEach(e=>e.onclick=ev=>{selected=ev.shiftKey?[...new Set([...selected,e.dataset.id])]:[e.dataset.id];renderAll()})}
const FIELDS=[['name','text'],['text','text'],['placeholder','text'],['src','text'],['x','number'],['y','number'],['width','number'],['height','number'],['padding','number'],['paddingTop','number'],['paddingRight','number'],['paddingBottom','number'],['paddingLeft','number'],['gap','number'],['fontSize','number'],['fontWeight','number'],['lineHeight','number'],['letterSpacing','number'],['rotation','number'],['borderRadius','number'],['borderWidth','number'],['opacity','number'],['background','text'],['color','color'],['borderColor','color'],['boxShadow','text'],['fontFamily','text'],['layout','select'],['align','select'],['justify','select'],['visible','boolean']];
function renderInspector(){const nodes=findAll();if(!nodes.length){inspector.innerHTML='<p>Select an element.</p>';return}const n=nodes[0];let html=`<h4>${nodes.length>1?nodes.length+' selected':esc(n.type)}</h4>`;for(const [k,t] of FIELDS){if(nodes.length===1 && !(k in n.props) && !['name','x','y','width','height','background','color','opacity','borderRadius','layout','align','justify','visible'].includes(k))continue;let v=n.props[k]??'';if(t==='select'){const opts=k==='layout'?['','absolute','row','column']:['','flex-start','center','flex-end','stretch','space-between','space-around'];html+=`<div class="field"><label>${k}</label><select data-prop="${k}">${opts.map(o=>`<option ${v===o?'selected':''}>${o}</option>`).join('')}</select></div>`}else if(t==='boolean')html+=`<div class="field"><label>${k}</label><input data-prop="${k}" type="checkbox" ${v!==false?'checked':''}></div>`;else html+=`<div class="field"><label>${k}</label><input data-prop="${k}" type="${t}" value="${esc(v)}"></div>`}
  html+=`<div class="row2"><button id="duplicate">Duplicate</button><button id="delete">Delete</button></div>`;inspector.innerHTML=html;
  inspector.querySelectorAll('[data-prop]').forEach(el=>el.oninput=()=>{pushHistory();const key=el.dataset.prop;let v=el.type==='checkbox'?el.checked:el.type==='number'?(el.value===''?undefined:Number(el.value)):el.value;for(const x of findAll()){if(v===undefined||v==='')delete x.props[key];else x.props[key]=v}renderCanvas();renderTree();renderInspect();scheduleSave()});
  $('#duplicate').onclick=()=>{pushHistory();const newSel=[];for(const id of [...selected]){const f=find(model.root,id);if(!f?.parent)continue;const c=clone(f.node);const newid=x=>{x.id=uid(x.type.toLowerCase());(x.children||[]).forEach(newid)};newid(c);f.parent.children.splice(f.parent.children.indexOf(f.node)+1,0,c);newSel.push(c.id)}selected=newSel;renderAll();scheduleSave()};
  $('#delete').onclick=()=>{pushHistory();for(const id of [...selected])remove(id);selected=[model.root.id];renderAll();scheduleSave()};
}
function remove(id){const f=find(model.root,id);if(!f?.parent)return null;return f.parent.children.splice(f.parent.children.indexOf(f.node),1)[0]}
function drop(e,targetId){const type=e.dataTransfer.getData('application/zigui-type'),existing=e.dataTransfer.getData('application/zigui-node'),target=find(model.root,targetId)?.node;if(!target||!TYPES[target.type]?.container)return;pushHistory();if(type){const n=node(type);target.children.push(n);selected=[n.id]}else if(existing&&existing!==targetId){const moved=remove(existing);if(moved&&!find(moved,targetId))target.children.push(moved);selected=[existing]}renderAll();scheduleSave()}
function renderTokens(){model.tokens=model.tokens||{};tokens.innerHTML=Object.entries(model.tokens).slice(0,200).map(([k,v])=>`<div class="token"><input value="${esc(k)}" disabled><input value="${esc(typeof v==='object'?JSON.stringify(v):v)}" data-token="${esc(k)}"></div>`).join('')||'<p class="hint">No tokens yet.</p>'}
function renderPrototype(){const n=findAll()[0];$('#protoAction').value=n?.prototype?.action??'';$('#protoTarget').value=n?.prototype?.target??'';$('#flows').innerHTML=collect(model.root).filter(x=>x.prototype?.action).map(x=>`<div>${esc(x.props?.name||x.type)} → ${esc(x.prototype.action)} ${esc(x.prototype.target||'')}</div>`).join('')||'<span class="hint">No flows.</span>'}
function collect(n,out=[]){out.push(n);for(const c of n.children||[])collect(c,out);return out}
function renderInspect(){const n=findAll()[0];$('#inspectJson').textContent=n?JSON.stringify(n,null,2):''}
function renderAll(){renderCanvas();renderTree();renderInspector();renderTokens();renderPrototype();renderInspect()}
function scheduleSave(){status.textContent='Unsaved';clearTimeout(saveTimer);saveTimer=setTimeout(save,220)}
async function save(){const r=await fetch('/api/model',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(model)}),d=await r.json();code.value=d.source??code.value;status.textContent='Saved'}
async function load(){model=await(await fetch('/api/model')).json();model.tokens=model.tokens||{};selected=[model.root.id];code.value=await(await fetch('/api/source')).text();renderAll()}
for(const t of Object.keys(TYPES)){const d=document.createElement('div');d.className='palette-item';d.draggable=true;d.textContent=t;d.ondragstart=e=>e.dataTransfer.setData('application/zigui-type',t);palette.appendChild(d)}
$('#importBtn').onclick=()=>$('#importFile').click();$('#importFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;status.textContent='Importing…';const base64=await new Promise(ok=>{const r=new FileReader();r.onload=()=>ok(String(r.result).split(',')[1]);r.readAsDataURL(f)});const res=await fetch('/api/import/file',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({filename:f.name,mime:f.type,base64})});const d=await res.json();if(!d.ok){alert(d.error);status.textContent='Import failed';return}model=d.model;selected=[model.root.id];code.value=d.source;renderAll();status.textContent='Imported'};
$('#figmaBtn').onclick=()=>$('#figmaDialog').showModal();$('#figmaImport').onclick=async e=>{e.preventDefault();status.textContent='Importing Figma…';const res=await fetch('/api/import/figma',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url:$('#figmaUrl').value,token:$('#figmaToken').value})});const d=await res.json();if(!d.ok){alert(d.error);status.textContent='Import failed';return}$('#figmaDialog').close();model=d.model;selected=[model.root.id];code.value=d.source;renderAll();status.textContent='Figma imported'};
$$('[data-device]').forEach(b=>b.onclick=()=>device.className='device '+b.dataset.device);$('#zoom').onchange=e=>{zoom=Number(e.target.value.replace('%',''))/100;$('#stage').style.transform=`scale(${zoom})`};$('#save').onclick=save;$('#undo').onclick=()=>{if(!history.length)return;future.push(clone(model));model=history.pop();renderAll();scheduleSave()};$('#redo').onclick=()=>{if(!future.length)return;history.push(clone(model));model=future.pop();renderAll();scheduleSave()};
$$('[data-left]').forEach(b=>b.onclick=()=>{$$('[data-left]').forEach(x=>x.classList.toggle('active',x===b));$('#layersPanel').hidden=b.dataset.left!=='layers';$('#assetsPanel').hidden=b.dataset.left!=='assets'});$$('[data-right]').forEach(b=>b.onclick=()=>{$$('[data-right]').forEach(x=>x.classList.toggle('active',x===b));for(const name of['design','prototype','inspect'])$('#'+name+'Panel').hidden=b.dataset.right!==name});
$('#applyPrototype').onclick=()=>{const n=findAll()[0];if(!n)return;pushHistory();n.prototype={action:$('#protoAction').value,target:$('#protoTarget').value};renderPrototype();scheduleSave()};$('#applyCode').onclick=async()=>{await fetch('/api/source',{method:'POST',headers:{'content-type':'text/plain'},body:code.value});status.textContent='Code applied'};$('#refreshCode').onclick=async()=>code.value=await(await fetch('/api/source')).text();
$('#addToken').onclick=()=>{const k=prompt('Token name','color.primary');if(!k)return;model.tokens[k]=prompt('Value','#0d63ce');renderTokens();scheduleSave()};$('#layerSearch').oninput=e=>{const q=e.target.value.toLowerCase();$$('.tree-node').forEach(x=>x.style.display=x.textContent.toLowerCase().includes(q)?'flex':'none')};
function align(mode){const ns=findAll();if(ns.length<2)return;pushHistory();const vals=ns.map(n=>Number(n.props.x||0));if(mode==='left'){const m=Math.min(...vals);ns.forEach(n=>n.props.x=m)}if(mode==='right'){const m=Math.max(...ns.map(n=>Number(n.props.x||0)+Number(n.props.width||0)));ns.forEach(n=>n.props.x=m-Number(n.props.width||0))}if(mode==='center'){const c=ns.reduce((a,n)=>a+Number(n.props.x||0)+Number(n.props.width||0)/2,0)/ns.length;ns.forEach(n=>n.props.x=c-Number(n.props.width||0)/2)}renderAll();scheduleSave()}
$('#alignLeft').onclick=()=>align('left');$('#alignCenter').onclick=()=>align('center');$('#alignRight').onclick=()=>align('right');$('#distribute').onclick=()=>{const ns=findAll().sort((a,b)=>Number(a.props.x||0)-Number(b.props.x||0));if(ns.length<3)return;pushHistory();const start=Number(ns[0].props.x||0),end=Number(ns.at(-1).props.x||0),step=(end-start)/(ns.length-1);ns.forEach((n,i)=>n.props.x=start+i*step);renderAll();scheduleSave()};
load();
